// <auto-generated />
using Antila.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Antila.Data.Migrations
{
    [DbContext(typeof(AntilaDbContext))]
    partial class AntilaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Antila.Core.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answer");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            Content = "Rick",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 6,
                            Content = "Deckard",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 7,
                            Content = "Jest",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 8,
                            Content = "Replikantem",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 9,
                            Content = "Zwykłą grypą",
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 10,
                            Content = "Groźną chorobą",
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 11,
                            Content = "Efektem ubocznym chemitrails",
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 12,
                            Content = "Atakiem USA na gospodarkę Chin",
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 17,
                            Content = "Norwid",
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 18,
                            Content = "Sienkiewicz",
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 19,
                            Content = "Traugutt",
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 20,
                            Content = "TZN",
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 21,
                            Content = "Martin Scorsese",
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 22,
                            Content = "Quentin Tarantino",
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 23,
                            Content = "Stanley Kubrick",
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 24,
                            Content = "David Fincher",
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 25,
                            Content = "Casablanca",
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 26,
                            Content = "Pulp Fiction",
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 27,
                            Content = "The Room",
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 28,
                            Content = "The Mark",
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 29,
                            Content = "Incepcja",
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 30,
                            Content = "Mulholland Drive",
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 31,
                            Content = "Joker",
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 32,
                            Content = "Django",
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 33,
                            Content = "Christopher Nolan",
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 34,
                            Content = "Anthony Russo",
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 35,
                            Content = "Zack Snyder",
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 36,
                            Content = "Joss Whedon",
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 37,
                            Content = "Japonia",
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 38,
                            Content = "Niemcy",
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 39,
                            Content = "Włochy",
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 40,
                            Content = "Hiszpania",
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 41,
                            Content = "Brazylia",
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 42,
                            Content = "Argentyna",
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 43,
                            Content = "Polska",
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 44,
                            Content = "Estonia",
                            QuestionId = 11
                        });
                });

            modelBuilder.Entity("Antila.Core.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CorrectId")
                        .HasColumnType("int");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TestId")
                        .IsUnique();

                    b.ToTable("Question");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Content = "Jak nazywa się postać w którą wciela się Harrison Ford w 'Łowcy Androidów'?",
                            CorrectId = 7,
                            TestId = 2
                        },
                        new
                        {
                            Id = 3,
                            Content = "Czym rzeczywiście jest choroba wywoływana przez COVID-19?",
                            CorrectId = 10,
                            TestId = 3
                        },
                        new
                        {
                            Id = 5,
                            Content = "Wymień częstochowską szkołę, w której brakuje drzwi w toalecie",
                            CorrectId = 18,
                            TestId = 5
                        },
                        new
                        {
                            Id = 6,
                            Content = "Wskaż reżysera, który zdobył najwięcej Oskarów za reżyserię",
                            CorrectId = 21,
                            TestId = 6
                        },
                        new
                        {
                            Id = 7,
                            Content = "Z którego filmu pochodzi cytat 'Oh, hi Mark!'?",
                            CorrectId = 27,
                            TestId = 7
                        },
                        new
                        {
                            Id = 8,
                            Content = "Wskaż film, który został wybrany przez redakcję BBC najlepszym filmem XX wieku ",
                            CorrectId = 30,
                            TestId = 8
                        },
                        new
                        {
                            Id = 9,
                            Content = "Który z wymienionych reżyserów słynie z używania w filmie praktycznych efektów specjalnych?",
                            CorrectId = 33,
                            TestId = 9
                        },
                        new
                        {
                            Id = 10,
                            Content = "W jakim z podanych krajów średnia długość życia wynosi najwięcej?",
                            CorrectId = 37,
                            TestId = 10
                        },
                        new
                        {
                            Id = 11,
                            Content = "Który z poniższych krajów nie jest zaliczany do 'wchodzącego i rozwijającego się' według Międzynarodowego Funduszu Walutowego?",
                            CorrectId = 44,
                            TestId = 11
                        });
                });

            modelBuilder.Entity("Antila.Core.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tests");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Category = "Kinematografia"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Społeczeństwo"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Społeczeństwo"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Kinematografia"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Kinematografia"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Kinematografia"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Kinematografia"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Społeczeństwo"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Społeczeństwo"
                        });
                });

            modelBuilder.Entity("Antila.Core.Answer", b =>
                {
                    b.HasOne("Antila.Core.Question", null)
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Antila.Core.Question", b =>
                {
                    b.HasOne("Antila.Core.Test", null)
                        .WithOne("Question")
                        .HasForeignKey("Antila.Core.Question", "TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
